### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by yangh-zzf-itcast** [Zi-YuanYang/CCNet#1]
你好作者，请问有预训练模型嘛？？

**Comment by Zi-YuanYang** [comment]
> 你好作者，请问有预训练模型嘛？？

感谢你的兴趣，因为一些原因目前我们不能提供预训练的模型，我们会尽量争取在不久之后公开预训练模型。

我们鼓励研究人员在自己预处理的数据集上进行训练并和所提出的方法进行比较，这样更能避免因为数据预处理方式不同造成性能差异的。
