### ISSUE TITLE
关于数据集方面的问题

### ISSUE THREAD

**Issue by lypliuyouping** [Zi-YuanYang/CCNet#2]
您好，看了您的源码，请问下代码相关的数据集可以公开吗，网上获取难度太大了

**Comment by Zi-YuanYang** [comment]
很抱歉，我无权共享这些数据集。然而，申请它们并不是十分困难，一般几天后就会收到回复。（可以在我们的论文中找到相关网站）

> 您好，看了您的源码，请问下代码相关的数据集可以公开吗，网上获取难度太大了
