### ISSUE TITLE
关于训练集和测试集的问题

### ISSUE THREAD

**Issue by lypliuyouping** [Zi-YuanYang/CCNet#4]
您好，我仔细阅读了您的源码，有个疑惑，是只分了训练和测试集吗，在计算val_accuracy的时候数据为啥是测试集呢，最后调用test还是用的测试集，不会过拟合吗，数据划分没有划分验证集

**Comment by Zi-YuanYang** [comment]
之前的在做close-set实验的时候，代码测试的时候是train_dataset，没有用test_dataset，是测得训练集上最好的结果和最后的结果。论文里所贴的结果均为最后一轮训练的结果，没有用最好的结果。
后来，因为审稿人提问关于open-set效果的问题，在对过拟合问题做验证的时候，把test_set改成了其他数据库的训练集作为测试集进行验证。所公开的代码忘记改回close-set了，谢谢提醒，已更正。
