### ISSUE TITLE
图像尺寸改变时报错

### ISSUE THREAD

**Issue by lypliuyouping** [Zi-YuanYang/CCNet#5]
您好，在我换数据集的时候，有的图像尺寸为150x150，我改变了尺寸输入，发现报错了
![image](https://github.com/Zi-YuanYang/CCNet/assets/47473211/107aa01d-c633-42d7-9389-45c857c34208)
经过报错发现好像在连接层这里，是写死的，请问如何解决呢
![image](https://github.com/Zi-YuanYang/CCNet/assets/47473211/7379f357-3660-44d3-813b-d6b3ffca91ac)

**Comment by Zi-YuanYang** [comment]
因为全连接层的维度是和前面特征维度相同，我的输入均是128*128，改了输入之后只需要把全连接层的13152改掉就可以了，看报错这个地方应该改成18624即可。下面的报错写了是因为矩阵维度不同导致的错误。

**Comment by Zi-YuanYang** [comment]
因为全连接层的维度是和前面特征维度相关，我的输入是128*128和你的维度不同，所以会报错。改了输入之后只需要把全连接层的13152改掉就可以了，看报错这个地方应该改成18624即可。下面的报错写了是因为矩阵维度不同导致的错误。
