### ISSUE TITLE
iitd数据集eer的结果不太行

### ISSUE THREAD

**Issue by lypliuyouping** [Zi-YuanYang/CCNet#6]
感谢之前您的细心回复，我换了iitd的数据集，
左手的图像为![image](https://github.com/Zi-YuanYang/CCNet/assets/47473211/8d50806c-3f14-476f-b589-182172cb2925)
右手的图像为
![image](https://github.com/Zi-YuanYang/CCNet/assets/47473211/f4fa90f3-11ba-46a2-80d3-f677e2d3db94)
分别取了左右手的每5张图作为一类，也就是1150张左图和1150右图
总共230类，epoch设置为200，但是测试的结果eer不太行，在2.6%左右，
![image](https://github.com/Zi-YuanYang/CCNet/assets/47473211/6dff7c64-45d9-4eb3-a687-8cf903c1b7b3)
数据集分割没问题
![image](https://github.com/Zi-YuanYang/CCNet/assets/47473211/67406e25-f7a2-4f35-b10a-7c25a1e81790)
不知道是哪里的问题，eer差距有点大，麻烦大佬了

**Comment by Zi-YuanYang** [comment]
大概率是因为图像预处理的方式不一样，我们所做的图像尺寸是128*128，你可以尝试把图像尺寸再进行裁剪、缩放等操作再进行尝试。
