### ISSUE TITLE
关于再tongji掌纹的训练和验证的accuracy问题

### ISSUE THREAD

**Issue by lypliuyouping** [Zi-YuanYang/CCNet#7]
发现一个奇怪的问题，为啥在训练和验证的loss以及accuracy的值绘图出来是这样的
![image](https://github.com/Zi-YuanYang/CCNet/assets/47473211/dbdd95eb-cd4b-4fad-a3cb-d55488df724c)
发现验证的accuracy高于训练的，大佬能方便指导下吗

**Comment by Zi-YuanYang** [comment]
是正常的，请仔细检查dataset代码。
