### ISSUE TITLE
ccnet.getFeatureCode()如何单独保存

### ISSUE THREAD

**Issue by Tyler-Chenn** [Zi-YuanYang/CCNet#8]
Hi：

    我在训练完模型后保存的是ccnet.foreard()的网络链路，但是在实际部署时我只需要ccnet.getFeatureCode()的网络链路。请问如何单独保存ccnet.getFeatureCode()的网络？期望您的答复。

**Comment by Zi-YuanYang** [comment]
> Hi：
> 
> ```
> 我在训练完模型后保存的是ccnet.foreard()的网络链路，但是在实际部署时我只需要ccnet.getFeatureCode()的网络链路。请问如何单独保存ccnet.getFeatureCode()的网络？期望您的答复。
> ```

forward和getfeaturecode的提取特征的网络参数是一致的，仅有最后一层分类层不同。建议一起保存，如果不要最后一层分类层，可以把最后一层参数不进行保存即可。
