### ISSUE TITLE
Pre Trained Model

### ISSUE THREAD

**Issue by Aksh97** [Zi-YuanYang/CCNet#9]
Hi There, 

Good work on this project! Can you pass along the pretrained model?

**Comment by Zi-YuanYang** [comment]
Thanks for your interest. We've released our pretrained checkpoints, pls find the share link in our updated readme. 

Because this method is designed under a close-set setting, we encourage the readers to train our method in your dataset.

**Comment by Aksh97** [comment]
Thanks for providing the pre-trained model. Now the issue is in the inference script. 
The models do not define the **compnet** in line 6. Can you please verify if the code is working given the model?

Also, what other command line parameters need to be passed for running inference.py?

**Comment by Zi-YuanYang** [comment]
> Thanks for providing the pre-trained model. Now the issue is in the inference script. The models do not define the **compnet** in line 6. Can you please verify if the code is working given the model?
> 
> Also, what other command line parameters need to be passed for running inference.py?

I'm sorry, thanks for your reminder. I uploaded the wrong version, and I've corrected it. Or you can ignore "reference.py", and use Function test() in train.py to evaluate your model.

**Comment by Zi-YuanYang** [comment]
> > Thanks for providing the pre-trained model. Now the issue is in the inference script. The models do not define the **compnet** in line 6. Can you please verify if the code is working given the model?
> > Also, what other command line parameters need to be passed for running inference.py?
> 
> I'm sorry, thanks for your reminder. I uploaded the wrong version, and I've corrected it. Or you can ignore "reference.py", and use Function test() in train.py to evaluate your model.

BTW, no other parameters are needed. Please correct the path and run.

**Comment by Aksh97** [comment]
That worked thanks.
